<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Daily Attendance Report - {{ $date }}</title>
    <style>
        body {
            font-family: 'Helvetica', Arial, sans-serif;
            font-size: 12pt;
            line-height: 1.2;
            color: #333333;
            margin: 0;
            padding: 0;
            background-color: #ffffff;
        }

        .container {
            width: 100%;
            margin: 0 auto;
            padding: 10px;
            background-color: #ffffff;
            border-radius: 4px;
        }

        .header {
            text-align: center;
            margin-bottom: 8px;
            border-bottom: 1px solid #0c0238;
            padding-bottom: 5px;
        }

        .header h1 {
            font-size: 14pt;
            font-weight: bold;
            color: #0c0238;
            margin: 5px 0;
        }

        .logo-placeholder {
            font-size: 14pt;
            font-weight: bold;
            color: #0c0238;
            text-transform: uppercase;
        }

        .summary {
            margin: 8px 0;
            padding: 5px;
            background-color: #0c0238;
            border-radius: 3px;
        }

        .summary p {
            margin: 2px 0;
            font-size: 8pt;
            color: #fff;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 0;
            font-size: 7pt; /* Increased for readability */
            table-layout: fixed;
        }

        th, td {
            border: none;
            padding: 3px 4px;
            text-align: left;
            vertical-align: top;
            overflow-wrap: normal; /* Prevent breaking inside words */
            white-space: normal; /* Allow wrapping at word boundaries */
        }

        th {
            background-color: #0c0238;
            color: #ffffff;
            font-weight: bold;
            text-transform: uppercase;
            border: none;
        }

        tr:nth-child(even) {
            background-color: #f9fafb;
        }

        tr:hover {
            background-color: #e5e7eb;
        }

        .footer {
            margin: 8px 0 0;
            text-align: center;
            font-size: 7pt;
            color: #666666;
            border-top: 0.5px solid #d1d5db;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo-placeholder">
                <img src="{{ asset('images/logo2x.png') }}" width="150" alt="">
                {{-- <p>ZENEROM HRM</p> --}}
            </div>
            <h1>Daily Attendance Report - {{ $date }}</h1>
        </div>

        <div class="summary">
            <p><strong>Total Employees:</strong> {{ count($reportData) }}</p>
            <p><strong>Present:</strong> {{ count(array_filter($reportData, fn($row) => $row['Login Time'] !== 'Absent')) }}</p>
            <p><strong>Leaves:</strong> {{ array_sum(array_column($reportData, 'Leave Count')) }}</p>
            <p><strong>WFH:</strong> {{ array_sum(array_column($reportData, 'WFH Count')) }}</p>
            <p><strong>Half Days:</strong> {{ array_sum(array_column($reportData, 'Half Day Count')) }}</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th style="width: 8%;">ID</th>
                    <th style="width: 12%;">Name</th>
                    <th style="width: 10%;">Dept</th>
                    <th style="width: 8%;">Role</th>
                    <th style="width: 10%;">Login Time</th>
                    <th style="width: 10%;">Logout Time</th>
                    <th style="width: 10%;">Work Hours</th>
                    <th style="width: 10%;">Break Hours</th>
                    <th style="width: 10%;">Mode</th>
                    <th style="width: 22%;">Tasks</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($reportData as $row)
                    <tr>
                        <td style="width: 8%;">{{ $row['Employee ID'] }}</td>
                        <td style="width: 12%;">{{ $row['Name'] }}</td>
                        <td style="width: 10%;">{{ $row['Department'] }}</td>
                        <td style="width: 8%;">{{ $row['Role'] }}</td>
                        <td style="width: 10%;">{{ $row['Login Time'] }}</td>
                        <td style="width: 10%;">{{ $row['Logout Time'] }}</td>
                        <td style="width: 10%;">{{ $row['Work Hours'] }}</td>
                        <td style="width: 10%;">{{ $row['Break Hours'] }}</td>
                        <td style="width: 10%;">{{ $row['Mode'] }}</td>
                        <td style="width: 22%;">{{ $row['Tasks'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            Generated by {{ config('app.name') }} on {{ \Carbon\Carbon::now('Asia/Kolkata')->format('d M Y h:i:s A') }}
        </div>
    </div>
</body>
</html>
