<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Daily Attendance Report - {{ $date }}</title>
    <style>
        body {
            font-family: 'Helvetica', Arial, sans-serif;
            font-size: 12pt;
            line-height: 1.2;
            color: #333333;
            margin: 0;
            padding: 0;
            background-color: #ffffff;
        }

        .container {
            width: 100%;
            margin: 0 auto;
            padding: 10px;
            background-color: #ffffff;
            border-radius: 4px;
        }

        .header {
            text-align: center;
            margin-bottom: 8px;
            border-bottom: 1px solid #0c0238;
            padding-bottom: 5px;
        }

        .header h1 {
            font-size: 14pt;
            font-weight: bold;
            color: #0c0238;
            margin: 5px 0;
        }

        .logo-placeholder {
            font-size: 12pt;
            font-weight: bold;
            color: #333333;
            text-transform: uppercase;
        }

        .summary {
            margin: 8px 0;
            padding: 5px;
            background-color: #e8f0fe;
            border-radius: 3px;
        }

        .summary p {
            margin: 2px 0;
            font-size: 8pt;
            color: #333333;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 0;
            font-size: 6pt;
            table-layout: fixed;
        }

        th, td {
            border: none;
            padding: 3px 4px;
            text-align: left;
            vertical-align: top;
            word-wrap: break-word;
            word-break: break-word;
            white-space: normal;
        }

        th {
            background-color: #0c0238;
            color: #ffffff;
            font-weight: bold;
            text-transform: uppercase;
            border: none;
        }

        tr:nth-child(even) {
            background-color: #f9fafb;
        }

        tr:hover {
            background-color: #e5e7eb;
        }

        .footer {
            margin: 8px 0 0;
            text-align: center;
            font-size: 7pt;
            color: #666666;
            border-top: 0.5px solid #d1d5db;
            padding-top: 5px;
        }

        .status-approved { color: #28a745; }
        .status-pending { color: #f0ad4e; }
        .status-rejected { color: #dc3545; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="logo-placeholder">ZENEROM HRM</div>
            <h1>Daily Attendance Report - {{ $date }}</h1>
        </div>

        <div class="summary">
            <p><strong>Total Employees:</strong> {{ count($reportData) }}</p>
            <p><strong>Present:</strong> {{ count(array_filter($reportData, fn($row) => $row['Login Time'] !== 'Absent')) }}</p>
            <p><strong>Absent:</strong> {{ count(array_filter($reportData, fn($row) => $row['Login Time'] === 'Absent')) }}</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Employee ID</th>
                    <th>Name</th>
                    <th>Department</th>
                    <th>Role</th>
                    <th>Login Time</th>
                    <th>Logout Time</th>
                    <th>Work Hours</th>
                    <th>Break Hours</th>
                    <th>Mode</th>
                    <th>Tasks</th>
                    <th>Approval Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($reportData as $row)
                    <tr>
                        <td>{{ $row['Employee ID'] }}</td>
                        <td>{{ $row['Name'] }}</td>
                        <td>{{ $row['Department'] }}</td>
                        <td>{{ $row['Role'] }}</td>
                        <td>{{ $row['Login Time'] }}</td>
                        <td>{{ $row['Logout Time'] }}</td>
                        <td>{{ $row['Work Hours'] }}</td>
                        <td>{{ $row['Break Hours'] }}</td>
                        <td>{{ $row['Mode'] }}</td>
                        <td>{{ $row['Tasks'] }}</td>
                        <td class="{{ 'status-' . strtolower($row['Approval Status'] ?? 'pending') }}">{{ $row['Approval Status'] ?? 'Pending' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            Generated by {{ config('app.name') }} on {{ \Carbon\Carbon::now('Asia/Kolkata')->format('d M Y h:i:s A') }}
        </div>
    </div>
</body>
</html>
